#ifndef HASHCODES_H
#define HASHCODES_H

// because this gets included into lua-internals too
#if defined(KEYSTRING_INCLUDE_DEBUG_INFO) && defined(__cplusplus)

struct CHashCode
{
	CHashCode(unsigned int code, const char* str) : code_(code), str_(str) {}
	unsigned int code_;
	const char*  str_;
};

#define HASH_DECLARE_HASHED_STRING(code, str) CHashCode((code), (str))
#define HASH_GET_CODE(code) (code.code_)

#else

#define HASH_DECLARE_HASHED_STRING(code, str) code
#define HASH_GET_CODE(code) (code)

#endif

#define HASH_STRING_NULL 0xeca1ee04

#define HASH_STRING_DIFFUSEIRRADIANCE HASH_DECLARE_HASHED_STRING( 0xf7e1a94d, "DiffuseIrradiance" )
#define HASH_STRING_TOLERANCE HASH_DECLARE_HASHED_STRING( 0x1a659914, "Tolerance" )
#define HASH_STRING_FUNCTIONSCRIPT HASH_DECLARE_HASHED_STRING( 0x4f7e0eda, "FunctionScript" )
#define HASH_STRING_SCALE HASH_DECLARE_HASHED_STRING( 0xd278f57f, "Scale" )
#define HASH_STRING_OFFSET HASH_DECLARE_HASHED_STRING( 0xa1593019, "Offset" )
#define HASH_STRING_CURVE_NODES HASH_DECLARE_HASHED_STRING( 0xf0e69d40, "CurveNodes" )

// Effect trail	simple
#define HASH_STRING_FADEPALETTE HASH_DECLARE_HASHED_STRING( 0x9810cd1a, "FadePalette" )
#define HASH_STRING_CROSSPALETTE HASH_DECLARE_HASHED_STRING( 0x3bb0c0a0, "CrossPalette" )
#define HASH_STRING_TEXTURENAME HASH_DECLARE_HASHED_STRING( 0x7e8d7479, "TextureName" )
#define HASH_STRING_FADETIME HASH_DECLARE_HASHED_STRING( 0x74bbf1bb, "FadeTime" )
#define HASH_STRING_EDGESPERSECOND HASH_DECLARE_HASHED_STRING( 0xd4fcb55d, "EdgesPerSecond" )
#define HASH_STRING_EDGEDEFINITION HASH_DECLARE_HASHED_STRING( 0x9cba54ef, "EdgeDefinition" )
//Effect trail line
#define HASH_STRING_LIFETIME HASH_DECLARE_HASHED_STRING( 0x9b5c021f, "LifeTime" )
#define HASH_STRING_EMITPERSECOND HASH_DECLARE_HASHED_STRING( 0xa330e02b, "EmitPerSecond" )
// Emission function
#define HASH_STRING_EMISSIONFUNCTION HASH_DECLARE_HASHED_STRING( 0x461c9dfa, "EmissionFunction" )
#define HASH_STRING_LOOPCOUNT HASH_DECLARE_HASHED_STRING( 0xdc7d04e3, "LoopCount" )
#define HASH_STRING_EMITPERLOOP HASH_DECLARE_HASHED_STRING( 0x177375d6, "EmitPerLoop" )
#define HASH_STRING_LOOPDURATION HASH_DECLARE_HASHED_STRING( 0xb82b00c8, "LoopDuration" )

#define HASH_STRING_ROOT HASH_DECLARE_HASHED_STRING( 0xdf9eeb10, "ROOT"	)

// Particle movement
#define HASH_STRING_VELOCITYSCALECURVE HASH_DECLARE_HASHED_STRING( 0xb908729c, "VelocityScaleCurve" )
#define HASH_STRING_ROCKETACCMIN HASH_DECLARE_HASHED_STRING( 0xa6fe6b8b, "RocketAccMin" )
#define HASH_STRING_ROCKETACCMAX HASH_DECLARE_HASHED_STRING( 0x9af354d2, "RocketAccMax" )
#define HASH_STRING_ACCELERATIONX HASH_DECLARE_HASHED_STRING( 0x3c9e5c40, "AccelerationX" )
#define HASH_STRING_ACCELERATIONY HASH_DECLARE_HASHED_STRING( 0x4b996cd6, "AccelerationY" )
#define HASH_STRING_ACCELERATIONZ HASH_DECLARE_HASHED_STRING( 0xd2903d6c, "AccelerationZ" )
#define HASH_STRING_STEERYAW HASH_DECLARE_HASHED_STRING( 0x4064850e, "SteerYaw" )
#define HASH_STRING_STEERPITCH HASH_DECLARE_HASHED_STRING( 0xc40a3f8c, "SteerPitch" )

// Psystem
#define HASH_STRING_SIZEFUNCTIONMIN HASH_DECLARE_HASHED_STRING( 0xd0712bba, "SizeFunctionMin" )
#define HASH_STRING_SIZEFUNCTIONMAX HASH_DECLARE_HASHED_STRING( 0xec7c14e3, "SizeFunctionMax" )
#define HASH_STRING_COLOURFUNCTION HASH_DECLARE_HASHED_STRING( 0x4ca41683, "ColourFunction" )
#define HASH_STRING_TEXTURENAME HASH_DECLARE_HASHED_STRING( 0x7e8d7479, "TextureName" )
#define HASH_STRING_RANDOMSEED HASH_DECLARE_HASHED_STRING( 0xde51333, "RandomSeed" )
#define HASH_STRING_BOUNCEPLANE HASH_DECLARE_HASHED_STRING( 0x61d2b8db, "BouncePlane" )
#define HASH_STRING_USEHAVOK HASH_DECLARE_HASHED_STRING( 0x81c2d1df, "UseHavok" )
#define HASH_STRING_PARTICLELIFETIME HASH_DECLARE_HASHED_STRING( 0x51c5883d, "ParticleLifeTime" )
#define HASH_STRING_SORTEDPARTICLES HASH_DECLARE_HASHED_STRING( 0xc1470bcf, "SortedParticles" )
#define HASH_STRING_USERANDATLASTEX HASH_DECLARE_HASHED_STRING( 0xed447817, "UseRandAtlasTex" )
#define HASH_STRING_SPAWNDEF HASH_DECLARE_HASHED_STRING( 0x35771a1b, "SpawnDef" )
#define HASH_STRING_PARTICLEDEF HASH_DECLARE_HASHED_STRING( 0x2f101f6c, "ParticleDef" )
#define HASH_STRING_EMITTERDEF HASH_DECLARE_HASHED_STRING( 0xd5d6d358, "EmitterDef" )
#define HASH_STRING_ADVANCEDMOVEMENT HASH_DECLARE_HASHED_STRING( 0xcc457012, "AdvancedMovement" )
#define HASH_STRING_RS_ HASH_DECLARE_HASHED_STRING( 0x22c6df6b, "RS." )

// Combat effect
#define HASH_STRING_LUAFUNCTIONSFILE HASH_DECLARE_HASHED_STRING( 0xb992867d, "LuaFunctionsFile" )

// Physics system
#define HASH_STRING_STATIC HASH_DECLARE_HASHED_STRING( 0x7893d2ec, "Static" )
#define HASH_STRING_STATICENTITYONLY HASH_DECLARE_HASHED_STRING( 0xb67f278b, "StaticEntityOnly" )
#define HASH_STRING_SOFT HASH_DECLARE_HASHED_STRING( 0x204775b6, "Soft" )
#define HASH_STRING_ANIMATED HASH_DECLARE_HASHED_STRING( 0x680d527a, "Animated" )
#define HASH_STRING_RIGID HASH_DECLARE_HASHED_STRING( 0x8e5884ca, "Rigid" )
#define HASH_STRING_RAGDOLL HASH_DECLARE_HASHED_STRING( 0x44e04a2c, "Ragdoll" )
#define HASH_STRING_DEFBYSCRIPT HASH_DECLARE_HASHED_STRING( 0x52f960a3, "DefByScript" )

// Ragdoll physics material name
#define HASH_STRING_PELVIS_MATERIAL HASH_DECLARE_HASHED_STRING( 0x3872dc80, "Generic_PelvisPhysicsMaterial" )
#define HASH_STRING_SPINE_MATERIAL HASH_DECLARE_HASHED_STRING( 0x12d8e66b, "Generic_SpinePhysicsMaterial" )
#define HASH_STRING_HEAD_MATERIAL HASH_DECLARE_HASHED_STRING( 0xe0e625f0, "Generic_HeadPhysicsMaterial" )
#define HASH_STRING_L_ARM_MATERIAL HASH_DECLARE_HASHED_STRING( 0xc6d08b03, "Generic_LArmPhysicsMaterial" )
#define HASH_STRING_R_ARM_MATERIAL HASH_DECLARE_HASHED_STRING( 0x41efa69f, "Generic_RArmPhysicsMaterial" )
#define HASH_STRING_L_LEG_MATERIAL HASH_DECLARE_HASHED_STRING( 0xf60b1bf2, "Generic_LLegPhysicsMaterial" )
#define HASH_STRING_R_LEG_MATERIAL HASH_DECLARE_HASHED_STRING( 0x7134366e, "Generic_RLegPhysicsMaterial" )

// SpeedTree trunk physics material name
#define HASH_STRING_SPEEDTREE_TRUNK HASH_DECLARE_HASHED_STRING( 0xb2a3458d, "WOOD_TRUNK" )


// Hair
#define HASH_STRING_NBSTEPPERFRAME HASH_DECLARE_HASHED_STRING( 0x70e336aa, "NbStepPerFrame" )
#define HASH_STRING_JOINTDEBUG HASH_DECLARE_HASHED_STRING( 0xf9ef12d4, "JointDebug" )
#define HASH_STRING_HAIR_DEFAULT_GLOBAL HASH_DECLARE_HASHED_STRING( 0x1285489, "hair_default_global" )

// Camera
#define HASH_STRING_ANON_CAM HASH_DECLARE_HASHED_STRING( 0xe6c87a5a, "Anon_Cam" )
#define HASH_STRING_THE_CAMERA_WITH_NO_NAME HASH_DECLARE_HASHED_STRING( 0x270b0538, "The Camera with No Name" )
#define HASH_STRING__NULL_CAM__ HASH_DECLARE_HASHED_STRING( 0x8d108823, "*Null Cam!*" )
#define HASH_STRING_DEBUG_CHASE_CAM HASH_DECLARE_HASHED_STRING( 0xc9e85b3, "Debug Chase Cam" ) 
#define HASH_STRING_DEBUG_TOP_DOWN_CAM HASH_DECLARE_HASHED_STRING( 0x7b7fb282, "Debug Top-Down Cam" ) 
#define HASH_STRING__CHASE_AIM_COMBO_CAM_ HASH_DECLARE_HASHED_STRING( 0x87851d15, "*Chase/Aim Combo Cam*" ) 
#define HASH_STRING__CHASE_CAM_ HASH_DECLARE_HASHED_STRING( 0xf11857d9, "*Chase Cam*" )
#define HASH_STRING__AIM_CAM_ HASH_DECLARE_HASHED_STRING( 0x4bc79151, "*Aim Cam*" ) 
#define HASH_STRING__GENERIC_COOLCAM_ HASH_DECLARE_HASHED_STRING( 0x33227bdd, "*Generic CoolCam*" ) 
#define HASH_STRING__AFTERTOUCH_CAM_ HASH_DECLARE_HASHED_STRING( 0x57897d19, "*Aftertouch Cam*" ) 
#define HASH_STRING__TURRET_CAM_ HASH_DECLARE_HASHED_STRING( 0xddab1ea4, "*Turret Cam*" )
#define HASH_STRING__AERIAL_COMBO_CAM_ HASH_DECLARE_HASHED_STRING( 0xe88007f9, "*Aerial Combo Cam*" )
#define HASH_STRING_CAMVIEW HASH_DECLARE_HASHED_STRING( 0xcaf1fbca, "CamView" )

// Entity
#define HASH_STRING_NAME HASH_DECLARE_HASHED_STRING( 0x1ee2ec7, "Name" )
#define HASH_STRING_THEENTITYWITHNONAME HASH_DECLARE_HASHED_STRING( 0xcc6cf63, "TheEntityWithNoName" )
#define HASH_STRING_ANIMATIONCONTAINER HASH_DECLARE_HASHED_STRING( 0xd4ccefe2, "AnimationContainer" )

// LUA attribute table
#define HASH_STRING_SHAREDATTRIBUTES HASH_DECLARE_HASHED_STRING( 0x79a8edbc, "SharedAttributes" )
#define HASH_STRING_TYPE HASH_DECLARE_HASHED_STRING( 0xd31307e8, "Type" )
#define HASH_STRING_ENTITY HASH_DECLARE_HASHED_STRING( 0xf67bbea1, "Entity" )
#define HASH_STRING_ENT HASH_DECLARE_HASHED_STRING( 0xdaf99aca, "Ent" )
#define HASH_STRING_BREAKKY HASH_DECLARE_HASHED_STRING( 0xcef7df75, "Breakky" )
#define HASH_STRING_THINK HASH_DECLARE_HASHED_STRING( 0xad059f57, "think" )

// Message handler
#define HASH_STRING_MSG HASH_DECLARE_HASHED_STRING( 0xaf38e6b0, "Msg" )
#define HASH_STRING_DATA HASH_DECLARE_HASHED_STRING( 0xf23ea3a2, "Data" )
#define HASH_STRING_OTHER HASH_DECLARE_HASHED_STRING( 0xe766e5db, "Other" )
#define HASH_STRING_SENDER HASH_DECLARE_HASHED_STRING( 0xa753b006, "Sender" )

// messages
#define HASH_STRING_MSG_AWARE_GAINED_LOCKON HASH_DECLARE_HASHED_STRING( 0xaa7ef425, "msg_aware_gained_lockon" )
#define HASH_STRING_MSG_AWARE_LOST_LOCKON HASH_DECLARE_HASHED_STRING( 0x22010be9, "msg_aware_lost_lockon" )
#define HASH_STRING_MSG_WALK_RUN_STOPPED HASH_DECLARE_HASHED_STRING( 0x75735af6, "msg_walk_run_stopped" )
#define HASH_STRING_MSG_CONTROL_END HASH_DECLARE_HASHED_STRING( 0xda583d1c, "msg_control_end" )
#define HASH_STRING_MSG_EXTERNAL_CONTROL_START HASH_DECLARE_HASHED_STRING( 0x9a554f17, "msg_external_control_start" )
#define HASH_STRING_MSG_NINJA_SEQUENCE_DIE HASH_DECLARE_HASHED_STRING( 0x906b238a, "msg_ninja_sequence_die" )
#define HASH_STRING_MSG_NINJA_SEQUENCE_FAIL HASH_DECLARE_HASHED_STRING( 0x4156fa51, "msg_ninja_sequence_fail" )
#define HASH_STRING_MSG_EXTERNAL_CONTROL_END HASH_DECLARE_HASHED_STRING( 0xf10a1d60, "msg_external_control_end" )
#define HASH_STRING_MSG_COLLAPSED HASH_DECLARE_HASHED_STRING( 0x4ffafa2a, "msg_collapsed" )
#define HASH_STRING_MSG_ACTION HASH_DECLARE_HASHED_STRING( 0x8fffa94, "msg_action" )
#define HASH_STRING_MSG_RUNNING_ACTION HASH_DECLARE_HASHED_STRING( 0x8af622b5, "msg_running_action" )
#define HASH_STRING_MSG_EXITSTATE HASH_DECLARE_HASHED_STRING( 0x591d23ee, "msg_exitstate" )

// Lua types
#define HASH_STRING__TYPE HASH_DECLARE_HASHED_STRING( 0x2e04d8cd, "_type" )

//BS
#define HASH_STRING_BSANIMS HASH_DECLARE_HASHED_STRING( 0xdb2e0a82, "BSAnims" )

// hero
#define HASH_STRING_COMBATDEFINITION HASH_DECLARE_HASHED_STRING( 0x6e27a5d3, "CombatDefinition" )
#define HASH_STRING_AWARENESSDEFINITION HASH_DECLARE_HASHED_STRING( 0xee0ea5ff, "AwarenessDefinition" )
#define HASH_STRING_SCENEELEMENTDEF HASH_DECLARE_HASHED_STRING( 0x554817b3, "SceneElementDef" )
#define HASH_STRING_INITPOS HASH_DECLARE_HASHED_STRING( 0xb65425a8, "InitPos" )
#define HASH_STRING_ANIMATIONCONTAINER HASH_DECLARE_HASHED_STRING( 0xd4ccefe2, "AnimationContainer" )
#define HASH_STRING_COLLISIONHEIGHT HASH_DECLARE_HASHED_STRING( 0xc7b4f103, "CollisionHeight" )
#define HASH_STRING_COLLISIONRADIUS HASH_DECLARE_HASHED_STRING( 0x9857a56, "CollisionRadius" )
#define HASH_STRING_WEAPONCONSTRUCTION HASH_DECLARE_HASHED_STRING( 0x6af3795e, "WeaponConstruction" )
#define HASH_STRING_HAIRCONSTRUCTION HASH_DECLARE_HASHED_STRING( 0xf2ba054b, "HairConstruction" )
#define HASH_STRING_PAD HASH_DECLARE_HASHED_STRING( 0x5a3bf7fa, "Pad" )
#define HASH_STRING_INITIALSYSTEMSTATE HASH_DECLARE_HASHED_STRING( 0x9fa79923, "InitialSystemState" )

// Collision Effect System
#define HASH_STRING_COLLISIONTYPE	HASH_DECLARE_HASHED_STRING( 0x2526ac72, "CollisionType" )
#define HASH_STRING_MATERIALTYPE	HASH_DECLARE_HASHED_STRING( 0x3073d91c, "MaterialType" )
#define HASH_STRING_MATERIALTYPE1	HASH_DECLARE_HASHED_STRING( 0x45ef2fac, "MaterialType1" )
#define HASH_STRING_MATERIALTYPE2	HASH_DECLARE_HASHED_STRING( 0xdce67e16, "MaterialType2" )
#define HASH_STRING_MASSTYPE		HASH_DECLARE_HASHED_STRING( 0x3be87280, "MassType" )
#define HASH_STRING_MASSTYPE1		HASH_DECLARE_HASHED_STRING( 0xbc5d6b68, "MassType1" )
#define HASH_STRING_MASSTYPE2		HASH_DECLARE_HASHED_STRING( 0x25543ad2, "MassType2" )

// Style events
#define HASH_STRING_EVENTKO					HASH_DECLARE_HASHED_STRING( 0x85e6e6cd, "EventKO" )
#define HASH_STRING_EVENTKILL				HASH_DECLARE_HASHED_STRING( 0x86b15822, "EventKill" )
#define HASH_STRING_EVENTGRAB				HASH_DECLARE_HASHED_STRING( 0x8e02f841, "EventGrab" )
#define HASH_STRING_EVENTRECOIL				HASH_DECLARE_HASHED_STRING( 0x8935f497, "EventRecoil" )
#define HASH_STRING_EVENTSTAGGER			HASH_DECLARE_HASHED_STRING( 0xda3c1445, "EventStagger" )
#define HASH_STRING_EVENTBLOCKSTAGGER		HASH_DECLARE_HASHED_STRING( 0x7a9c6618, "EventBlockStagger" )
#define HASH_STRING_EVENTCOUNTER			HASH_DECLARE_HASHED_STRING( 0x22fb1932, "EventCounter" )
#define HASH_STRING_EVENTEVADE				HASH_DECLARE_HASHED_STRING( 0x9f758598, "EventEvade" )
#define HASH_STRING_EVENTAERIAL				HASH_DECLARE_HASHED_STRING( 0x288642e2, "EventAerial" )
#define HASH_STRING_EVENTCOMBO				HASH_DECLARE_HASHED_STRING( 0x82b1dfd1, "EventCombo" )
#define HASH_STRING_EVENTGOTKOED			HASH_DECLARE_HASHED_STRING( 0xa0d2f4bd, "EventGotKOed" )
#define HASH_STRING_EVENTGOTKILLED			HASH_DECLARE_HASHED_STRING( 0x8474b817, "EventGotKilled" )
#define HASH_STRING_EVENTGOTIMPACTSTAGGERED	HASH_DECLARE_HASHED_STRING( 0xe7a89b29, "EventGotImpactStaggered" )
#define HASH_STRING_EVENTGOTBLOCKSTAGGERED	HASH_DECLARE_HASHED_STRING( 0x80575a95, "EventGotBlockStaggered" )
#define HASH_STRING_EVENTFAILNS				HASH_DECLARE_HASHED_STRING( 0xe5aad3bf, "EventFailNS" )
#define HASH_STRING_EVENTSUCCESSNS			HASH_DECLARE_HASHED_STRING( 0xc598b571, "EventSuccessNS" )

// Tutorial events
#define HASH_STRING_SPEED_MEDIUM		HASH_DECLARE_HASHED_STRING( 0xa4e4903f, "SPEED_MEDIUM" )
#define HASH_STRING_SPEED_FAST			HASH_DECLARE_HASHED_STRING( 0x577716ef, "SPEED_FAST" )
#define HASH_STRING_RANGE_MEDIUM		HASH_DECLARE_HASHED_STRING( 0x4a8514b4, "RANGE_MEDIUM" )
#define HASH_STRING_RANGE_FAST			HASH_DECLARE_HASHED_STRING( 0x2a7f539,	"RANGE_FAST" )
#define HASH_STRING_POWER_MEDIUM		HASH_DECLARE_HASHED_STRING( 0x77fb1bbb, "POWER_MEDIUM" )
#define HASH_STRING_POWER_FAST			HASH_DECLARE_HASHED_STRING( 0x2428f79c, "POWER_FAST" )
#define HASH_STRING_EVADE_STRIKE		HASH_DECLARE_HASHED_STRING( 0xb6fac4b0, "EVADE_STRIKE" )
#define HASH_STRING_GROUND_ATTACK		HASH_DECLARE_HASHED_STRING( 0x92588cfa, "GROUND_ATTACK" )
#define HASH_STRING_SPEED_MEDIUM_HIT	HASH_DECLARE_HASHED_STRING( 0x1ea8a333, "SPEED_MEDIUM_HIT" )
#define HASH_STRING_SPEED_FAST_HIT		HASH_DECLARE_HASHED_STRING( 0xa39c07e7, "SPEED_FAST_HIT" )
#define HASH_STRING_RANGE_MEDIUM_HIT	HASH_DECLARE_HASHED_STRING( 0xf998b4cc, "RANGE_MEDIUM_HIT" )
#define HASH_STRING_RANGE_FAST_HIT		HASH_DECLARE_HASHED_STRING( 0x913eef3f, "RANGE_FAST_HIT" )
#define HASH_STRING_POWER_MEDIUM_HIT	HASH_DECLARE_HASHED_STRING( 0x4373fbce, "POWER_MEDIUM_HIT" )
#define HASH_STRING_POWER_FAST_HIT		HASH_DECLARE_HASHED_STRING( 0x8619d31f, "POWER_FAST_HIT" )
#define HASH_STRING_EVADE_STRIKE_HIT	HASH_DECLARE_HASHED_STRING( 0xe7dfcda5, "EVADE_STRIKE_HIT" )
#define HASH_STRING_GROUND_ATTACK_HIT	HASH_DECLARE_HASHED_STRING( 0xcdcd933e, "GROUND_ATTACK_HIT" )
#define HASH_STRING_GRAB				HASH_DECLARE_HASHED_STRING( 0xc6f0e441, "GRAB" )
#define HASH_STRING_EVADE				HASH_DECLARE_HASHED_STRING( 0xa453574c, "EVADE" )
#define HASH_STRING_COUNTER				HASH_DECLARE_HASHED_STRING( 0x198959d,	"COUNTER" )
#define HASH_STRING_KILL				HASH_DECLARE_HASHED_STRING( 0xce434422, "KILL" )
#define HASH_STRING_KO					HASH_DECLARE_HASHED_STRING( 0x4bc827cf, "KO" )
#define HASH_STRING_AERIAL				HASH_DECLARE_HASHED_STRING( 0x926d5235, "AERIAL" )
#define HASH_STRING_SPEED_BLOCK			HASH_DECLARE_HASHED_STRING( 0xc6b9b078, "SPEED_BLOCK" )
#define HASH_STRING_RANGE_BLOCK			HASH_DECLARE_HASHED_STRING( 0xa95c177a, "RANGE_BLOCK" )
#define HASH_STRING_POWER_BLOCK			HASH_DECLARE_HASHED_STRING( 0xfc6cf1f,	"POWER_BLOCK" )
#define HASH_STRING_SPEED_STANCE		HASH_DECLARE_HASHED_STRING( 0xe06a96b4, "SPEED_STANCE" )
#define HASH_STRING_RANGE_STANCE		HASH_DECLARE_HASHED_STRING( 0xe0b123f,	"RANGE_STANCE" )
#define HASH_STRING_POWER_STANCE		HASH_DECLARE_HASHED_STRING( 0x33751d30, "POWER_STANCE" )
#define HASH_STRING_SUPERSTYLE_ZERO		HASH_DECLARE_HASHED_STRING( 0x787e9ef9, "SUPERSTYLE_ZERO" )
#define HASH_STRING_SUPERSTYLE_ONE		HASH_DECLARE_HASHED_STRING( 0x39d6690,	"SUPERSTYLE_ONE" )
#define HASH_STRING_SUPERSTYLE_TWO		HASH_DECLARE_HASHED_STRING( 0x683b6a07, "SUPERSTYLE_TWO" )
#define HASH_STRING_SUPERSTYLE_THREE	HASH_DECLARE_HASHED_STRING( 0x751a0f0f, "SUPERSTYLE_THREE" )
#define HASH_STRING_SUPERSTYLE_FOUR		HASH_DECLARE_HASHED_STRING( 0x43610916, "SUPERSTYLE_FOUR" )
#define HASH_STRING_SUPERSTYLE_FIVE		HASH_DECLARE_HASHED_STRING( 0xef12a3a0, "SUPERSTYLE_FIVE" )
#define HASH_STRING_SUPERSTYLE_SIX		HASH_DECLARE_HASHED_STRING( 0x3ae6c69a, "SUPERSTYLE_SIX" )
#define HASH_STRING_SUPERSTYLE_SEVEN	HASH_DECLARE_HASHED_STRING( 0xa58b7a96, "SUPERSTYLE_SEVEN" )
#define HASH_STRING_SUPERSTYLE_EIGHT	HASH_DECLARE_HASHED_STRING( 0x55d5e97c, "SUPERSTYLE_EIGHT" )
#define HASH_STRING_SUPERSTYLE_NINE		HASH_DECLARE_HASHED_STRING( 0xa8bd1316, "SUPERSTYLE_NINE" )
#define HASH_STRING_SUPERSTYLE_SPECIAL	HASH_DECLARE_HASHED_STRING( 0x55bc54e9, "SUPERSTYLE_SPECIAL" )
#define HASH_STRING_VAULT				HASH_DECLARE_HASHED_STRING( 0xf79b746e, "VAULT" )
#define HASH_STRING_CROUCH				HASH_DECLARE_HASHED_STRING( 0x8f71cb61, "CROUCH" )
#define HASH_STRING_RELOAD				HASH_DECLARE_HASHED_STRING( 0xadbff62c, "RELOAD" )
#define HASH_STRING_FIRSTPERSON_FIRE	HASH_DECLARE_HASHED_STRING( 0x6a07f3be, "FIRSTPERSON_FIRE" )
#define HASH_STRING_THIRDPERSON_FIRE	HASH_DECLARE_HASHED_STRING( 0x4a7f0053, "THIRDPERSON_FIRE" )
#define HASH_STRING_FIRSTPERSON			HASH_DECLARE_HASHED_STRING( 0xed5b56f7, "FIRSTPERSON" )
#define HASH_STRING_THIRDPERSON			HASH_DECLARE_HASHED_STRING( 0x71e2003f, "THIRDPERSON" )
#define HASH_STRING_HEADSHOT			HASH_DECLARE_HASHED_STRING( 0xa3373e43, "HEADSHOT" )
#define HASH_STRING_AFTERTOUCH			HASH_DECLARE_HASHED_STRING( 0x815c97db, "AFTERTOUCH" )
#define HASH_STRING_MOUNT_TURRET		HASH_DECLARE_HASHED_STRING( 0xaa128a5c, "MOUNT_TURRET" )
#define HASH_STRING_DISMOUNT_TURRET		HASH_DECLARE_HASHED_STRING( 0x1d3c02c4, "DISMOUNT_TURRET" )

#endif
